### ISSUE TITLE
Bad version number in 2.1.0

### ISSUE THREAD

**Issue by zoggy** [mirage/ocaml-base64#10]
After installing base64 with opam:
````
$ ocamlfind query base64 -format "%v"
v2.1.1
````
The version number is not the same (2.1.1 instead of 2.1.0) and having 'v' at the beginning of the version number is not standard.

**Comment by hannesm** [comment]
I fixed the META issue in #11.  The 2.1.1 vs 2.1.0 -- maybe we should rename the thing in opam-repository (the url of 2.1.0 there points to v2.1.1.tbz)?

**Comment by hannesm** [comment]
this issue is not fixed, only a future release (or a local patch in opam-repository) will fix the META issue...
