### ISSUE TITLE
Real iso on B64

### ISSUE THREAD

**Issue by dinosaure** [mirage/ocaml-base64#20]
@hannesm get this behavior:

```ocaml
# B64.decode "Zm9vCg==";;
- : string = "foo\n"
# B64.decode "Zm9vCg=a";;
- : string = "foo\n"
```

A solution could be to put a optional argument to check strictly end of base64 encoded input.

**Comment by hannesm** [comment]
FWIW, more discussions about this:
- https://github.com/g2p/storage-unikernel/issues/17 mentions `docs state that extra zeros may be added on decoding` - but the implementation seems not to do that!?
- nocrypto had similar issues, fixed by https://github.com/mirleft/ocaml-nocrypto/pull/96

**Comment by hannesm** [comment]
> A solution could be to put a optional argument to check strictly end of base64 encoded input.

I'm interested to hear use cases where you want base64 without proper padding (I'm sure there are some protocols which just remove the `=` from the string, but IIUC this won't be handled by Base64.decode properly atm anyways).

**Comment by dinosaure** [comment]
Ok, I did a benchmark between the current version of `ocaml-base64` and a tuned version of `base64` available in `nocrypto` (mostly, from it, I avoided `Hashtbl` and use a `string` instead a `cstruct`). And I got this result:

```
Estimated testing time 2.66667m (16 benchmarks x 10s). Change using -quota SECS.
┌──────────┬──────────────┬─────────┬───────────┬──────────┬────────────┐
│ Name     │     Time/Run │ mWd/Run │  mjWd/Run │ Prom/Run │ Percentage │
├──────────┼──────────────┼─────────┼───────────┼──────────┼────────────┤
│ B64:0    │     166.75ns │  49.00w │           │          │      0.04% │
│ B64:10   │     502.07ns │  55.00w │           │          │      0.11% │
│ B64:50   │   1_957.82ns │  71.01w │           │          │      0.42% │
│ B64:100  │   3_405.78ns │  92.01w │           │          │      0.73% │
│ B64:500  │  12_527.07ns │ 258.00w │           │          │      2.69% │
│ B64:1000 │  22_862.22ns │ 468.00w │     0.24w │    0.24w │      4.90% │
│ B64:2500 │  62_308.51ns │  45.01w │ 1_047.02w │          │     13.36% │
│ B64:5000 │ 137_406.04ns │  45.04w │ 2_089.03w │          │     29.47% │
│ Old:0    │     106.60ns │   9.00w │           │          │      0.02% │
│ Old:10   │   1_198.17ns │  12.00w │           │          │      0.26% │
│ Old:50   │   5_350.12ns │  23.00w │           │          │      1.15% │
│ Old:100  │  10_174.44ns │  38.00w │           │          │      2.18% │
│ Old:500  │  56_043.60ns │ 154.00w │           │          │     12.02% │
│ Old:1000 │  92_715.26ns │ 301.00w │     0.11w │    0.11w │     19.88% │
│ Old:2500 │ 228_832.80ns │   5.00w │   733.05w │          │     49.08% │
│ Old:5000 │ 466_272.34ns │   5.00w │ 1_462.10w │    0.10w │    100.00% │
└──────────┴──────────────┴─────────┴───────────┴──────────┴────────────┘
```

I did a benchmark when I try to encode a random input and decode it then. The number next to `B64` or `Old` is the length of the random input.

As we can see, the `nocrypto`'s solution is faster than the current solution (`Old`). I rewrote `ocaml-base64` mostly because it raise `Not_found` exception when I parsed some e-mails. This exception told me nothing about the input (which is of course an invalid input). This exception came from `String.index`.

The new version is more explicit about errors and can tell you if it's a bad input or if the padding is wrong. I will make a PR soon.

**Comment by dinosaure** [comment]
Then, the new version fix the reproducible example as expected.
