### ISSUE TITLE
Make the error type open

### ISSUE THREAD

**Issue by copy** [mirage/ocaml-base64#38]
The type of results of functions in this module is ``(string, [ `Msg of string ]) result``. This makes them non-composable with other errors, for example:

```ocaml
let parse_sdns sdns =
  match strip_sdns_prefix sdns with
  | Error e -> Error e
  | Ok sdns ->
    match Base64.decode ~alphabet:Base64.uri_safe_alphabet ~pad:false sdns with
    | Error e ->
      (* This expression has type [ `Msg of string ] but an expression was expected of 
         type [> `Invalid_prefix ]
         The first variant type does not allow tag(s) `Invalid_prefix *)
      Error e
    | Ok a -> Ok a
```

Making the type open (i.e., ``(string, [> `Msg of string ]) result``) should fix the problem.

**Comment by dinosaure** [comment]
Agree with that, if you make a PR, I will happy to merge & release it.
